### ISSUE TITLE
`partition` partitions into tuples, not into chunks of original type

### ISSUE THREAD

**Issue by wrobell** [pytoolz/cytoolz#102]
Having a byte array
```
data = bytearray(range(1000))
```
I would like to partition it into chunks
```
chunks = partition(10, data)
```
and parse the chunks with `struct`
```
items = (struct.unpack('...', item) for item in chunks)
```
This does not work in Python 3. The `item` has to be a buffer not tuple, so a workaround is needed
```
items = (struct.unpack('...', bytes(item)) for item in chunks)
```

It would be great if above operation could be performed without the workaround.
Could `partition` and `partition_all` functions preserve the type of the input sequence?

**Comment by blakev** [comment]
@wrobell the current functionality is identical to the `toolz` package. Making a "preserve type" parameter would change the API.

**Comment by eriknw** [comment]
I'm -1 on trying to preserve type.  I prefer (and is it generally more Pythonic) to be explicit, and I don't think there is too much burden on the user to be explicit.  For example,
```python
In [1]: from toolz.curried import *

In [2]: pipe(
   ...:     bytearray(range(10)),
   ...:     partition_all(2),
   ...:     map(bytearray),  # <-- cast to new type from tuple
   ...:     # ...,  # do other operations like `struct.unpack` here
   ...:     list,
   ...: )
Out[2]: 
[bytearray(b'\x00\x01'),
 bytearray(b'\x02\x03'),
 bytearray(b'\x04\x05'),
 bytearray(b'\x06\x07'),
 bytearray(b'\x08\t')]
```

**Comment by wrobell** [comment]
To be honest, despite documentation I was surprised it did not preserve the type.

For example, consider slicing in Python
```
In [127]: list(range(10))[::4]
Out[127]: [0, 4, 8]      # list

In [128]: tuple(range(10))[::4]
Out[128]: (0, 4, 8)      # tuple
```

Also
```
In [119]: %timeit itz.count(pipe(itz.partition(10, 20 * list(range(20)))))
The slowest run took 4.27 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.06 µs per loop

In [120]: %timeit itz.count(pipe(itz.partition(10, 20 * list(range(20)), curried.map(bytearray))))
The slowest run took 4.70 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 13.2 µs per loop
```

**Comment by llllllllll** [comment]
I also would prefer not to preserve the type. It will not work for lazy iterators like partitioning a `map` or genexpr in which case we would fall back to tuple anyways. One thing we could do is add a `factory` keyword argument which defaults to tuple sort of like what we do with `dicttoolz`:
```python
>>> merge({'a': 1, 'b': 2}, {'c': 3, 'd': 4}, factory=collections.OrderedDict)
 OrderedDict([('a', 1), ('b', 2), ('c', 3), ('d', 4)])

>>> list(partition(2, (1, 2, 3, 4), factory=list))
[[1, 2], [3, 4]]
```

This would require us to not use `zip` though which might make it too slow for normal `toolz`

**Comment by eriknw** [comment]
Thanks for sharing your perspective!

This isn't performing slicing.  I guess it's most similar to `itertools.islice`, which returns an iterable and does not preserve type.  If the input iterable has `__getitem__` and `__len__` methods, would you prefer to use a slicing approach?

Also, as you demonstrated, returning tuples is pretty fast!  Benchmarks below use `cytoolz`:
```python
In [1]: import cytoolz as itz

In [2]: from cytoolz import curried

In [3]: %timeit itz.count(itz.partition(10, 20 * list(range(20))))
4.33 µs ± 89.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [4]: %timeit itz.count(bytearray(x) for x in itz.partition(10, 20 * list(range(20))))
36.4 µs ± 1.34 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [3]: %timeit itz.count(pipe(itz.partition(10, 20 * list(range(20))), curried.map(bytearray)))
47.2 µs ± 968 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```
Here we see that casting to `bytearray` is the slowest operation.  Using `curried.map` adds some overhead (about 30%) in the last example compared to a generator comprehension.

**Comment by eriknw** [comment]
What about having a method that performs slices as you want?  For example,
```python
from toolz.compatibility import zip_longest, range

def partition_with_slices(n, seq):
    bounds = zip_longest(range(0, len(seq), n), range(n, len(seq), n))
    return (seq[a:b] for a, b in bounds)
```
(this discussion probably belongs in a `toolz` issue, not in `cytoolz`)

**Comment by wrobell** [comment]
https://github.com/pytoolz/toolz/issues/377
