### ISSUE TITLE
'cytoolz.functoolz.Compose' object has no attribute '__module__'

### ISSUE THREAD

**Issue by djrtwo** [pytoolz/cytoolz#103]
When porting to cytoolz from toolz, I ran into the problem where the some previous library code was expecting `Compose` to have `__module__` defined. I'm new to the project, but would expect the goal to be to generally to be able to move to cytoolz from toolz without any issues.

Should this be defined in Compose? If so, I can work to add it.

**Comment by pipermerriam** [comment]
Any thoughts on whether this could be addressed?

Also, here's a cute puppy to thank you for your time.

![561447_cfad8a26d5063e659828371ef52d1317_large](https://user-images.githubusercontent.com/824194/30146274-6b2ab1e2-9354-11e7-93ea-507fefc75d66.jpg)

**Comment by eriknw** [comment]
Thanks for the report and the puppy!  And I'm sorry for the delay; I had a 5000+ mile road trip to plan and execute that just finished.

> I'm new to the project, but would expect the goal to be to generally to be able to move to cytoolz from toolz without any issues.

You're right, that is the goal, so any issue like this is greatly appreciated.

To clarify, it is `Compose` objects and not the `Compose` class that don't have `__module__` attribute`, right?  Taking a look now.

**Comment by djrtwo** [comment]
I believe is the `Compose` class. This is the original error (sorry hard to read)

![29049765-924efb76-7b9d-11e7-9388-f2b37669c19d](https://user-images.githubusercontent.com/1433595/30168934-7c8d93da-93b0-11e7-8fc3-b1007724d7fe.jpg)

I previously tried to import it and just monkey patch it but can't because it's compiled c-code.
```python
from cytoolz import (
    Compose
)

Compose.__module__ = "cytoolz.functoolz"
```
error:
> TypeError: can't set attributes of built-in/extension type 'cytoolz.functoolz.Compose'

I hope that helps. I'm a few weeks away from seeing the error so that's all the info I have without digging back in deeper.

**Comment by pipermerriam** [comment]
@eriknw no worries about the delay.  Thanks for taking a look and for maintaining an awesome library that I love.

**Comment by pipermerriam** [comment]
ping

**Comment by llllllllll** [comment]
the `__module__` is always `toolz.functoolz` for `toolz.functoolz.Compose`, is that actually useful to put in cytoolz?

**Comment by eriknw** [comment]
This is in.  Sorry for the delay.  I plan to do a release later today.

**Comment by pipermerriam** [comment]
Much appreciated @eriknw and @llllllllll

**Comment by eriknw** [comment]
You bet, and thanks for the puppy!

Sorry again for the excessive delay.  0.9.0 was just released if you want to give it a go.
