### ISSUE TITLE
cytoolz.get() produces "Segmentation fault" with numpy array

### ISSUE THREAD

**Issue by andyisimprovised** [pytoolz/cytoolz#104]
Hello,

The "Segmentation fault" is reproducible with the following code snippet

```python
import cytoolz
import numpy
x = numpy.asarray([0])
cytoolz.get(0, x)
```

Using the normal `toolz` module does not result in failure.  Using a normal python `list` object does not result in failure with `cytoolz`, either, as should be expected.

It should be said that I am running these versions of numpy and cytoolz:

```
numpy==1.13.1
cytoolz==0.8.2
```

**Comment by eriknw** [comment]
Wow, thanks!  I have a suspicion what's causing this.  This will motivate me to push out releases of toolz/cytoolz soon.

**Comment by eriknw** [comment]
Fixed!  I don't know how to add a test for this without requiring `numpy`, but I confirmed the segmentation fault and that this fixed it.

**Comment by andyisimprovised** [comment]
Yay!  Thank you.
