### ISSUE TITLE
release dates are off by a year

### ISSUE THREAD

**Issue by themusicgod1** [pytoolz/cytoolz#114]
not sure if this is a cytoolz thing or a github thing but this is what it shows:

 an hour ago
0.9.0

    d1d5474 zip tar.gz 

on Dec 11, 2016
0.8.2

    e6fb244 zip tar.gz 

on Dec 4, 2016
0.8.1

    ee44a59 zip tar.gz 

on Dec 4, 2016
0.8.0

    a75a268 zip tar.gz 

on Dec 4, 2016
0.7.5

    873771f zip tar.gz

**Comment by eriknw** [comment]
This is all correct.  0.9.0 was just released an hour ago.  The last release (0.8.2) was about a year ago.  We also didn't tag or have a "release" branch until last December, which is why there is a cluster of dates around Dec 4, 2016.

Closing.  If I misunderstood something, feel free to reopen.
