### ISSUE TITLE
Test failure: test_curried_doctests.test_doctests

### ISSUE THREAD

**Issue by FRidh** [pytoolz/cytoolz#116]
```
======================================================================
ERROR: test_curried_doctests.test_doctests
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/fpypv9j5xcnh2x5pv3hv59a3cqkl4cgc-python2.7-nose-1.3.7/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/nix/store/hzmv4zkz2wrl3kfr28n2hirfizlid5v4-python2.7-cytoolz-0.9.0/lib/python2.7/site-packages/cytoolz/tests/test_curried_doctests.py", line 10, in test_doctests
    assert doctest.testmod(cytoolz).failed == 0
  File "/nix/store/hr461qqci171p6k53wwz52ifyp2h9g9l-python-2.7.14/lib/python2.7/doctest.py", line 1910, in testmod
    for test in finder.find(m, name, globs=globs, extraglobs=extraglobs):
  File "/nix/store/hr461qqci171p6k53wwz52ifyp2h9g9l-python-2.7.14/lib/python2.7/doctest.py", line 926, in find
    self._find(tests, obj, name, module, source_lines, globs, {})
  File "/nix/store/hr461qqci171p6k53wwz52ifyp2h9g9l-python-2.7.14/lib/python2.7/doctest.py", line 995, in _find
    (type(val),))
ValueError: DocTestFinder.find: __test__ values must be strings, functions, methods, classes, or modules: <type 'cython_function_or_method'>
```

The failure occurs with Python 2.7, but not with 3.5 or 3.6.

Build log:
https://nix-cache.s3.amazonaws.com/log/gd87cl101zp1jm669ri024q85ivd9pnl-python2.7-cytoolz-0.9.0.drv

Build job:
https://hydra.nixos.org/build/66843545

**Comment by opoplawski** [comment]
Seeing the same thing with the fedora package: https://kojipkgs.fedoraproject.org//work/tasks/8172/23988172/build.log

**Comment by eriknw** [comment]
Thanks for the report.  We are currently using the workaround shown here:
https://github.com/cython/cython/wiki/FAQ#how-can-i-run-doctests-in-cython-code-pyx-files

This workaround is only needed for ancient versions of Cython, so we should be able to fix the problem by simply removing the workaround in our tests and rely on the `__test__` dict with string values that Cython kindly generates for us.

**Comment by eriknw** [comment]
Oh, the file "cytoolz/tests/test_curried_doctests.py" shouldn't have been bundled in the release, because it's unnecessary.  I had this file locally, and it accidentally got included.  My bad.  You can safely ignore that error.  Is this enough of a nuisance to warrant a micro-release?

**Comment by FRidh** [comment]
In Nixpkgs we can just remove the file, so its no problem, but if others encounter this as well then a new release may be a good idea.

**Comment by jjhelmus** [comment]
If the issue is just with the tarball of PyPI have you considered a [post-release](https://www.python.org/dev/peps/pep-0440/#post-releases)?  I believe that would allow the sdist on PyPI to be updated without a need to increment the version number.

**Comment by jakirkham** [comment]
Agreed a post-release would be nice. Just ran into this problem in conda-forge.

**Comment by eriknw** [comment]
My bad for letting this linger.  I just pushed 0.9.0.1 to PyPI (adding a post suffix seemed weird to me).

Thanks for everyone's engagement and sorry for causing unnecessary hassle.
