### ISSUE TITLE
Cant install Cytoolz on Win10

### ISSUE THREAD

**Issue by freezepro** [pytoolz/cytoolz#121]
getting by next line and then error, used to install separately or as part of other projects. Please help

  copying cytoolz\tests\test_utils.py -> build\lib.win-amd64-3.5\cytoolz\tests
    running build_ext
    building 'cytoolz.dicttoolz' extension
    error: [WinError 2] The system cannot find the file specified

    ---------------
-------------------------
Command ""c:\program files\python 3.5\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-ixcikn1j\\cytoolz\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Admin\AppData\Local\Temp\pip-record-zp8n943t\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Admin\AppData\Local\Temp\pip-install-ixcikn1j\cytoolz\

**Comment by eriknw** [comment]
Thanks for the report @freezepro and sorry for my delay.  Have you found a solution to this?  I'm unsure how to help.  I don't recall encountering this before.

**Comment by Super-SaiyanSandwich** [comment]
Don't know if a solution was ever found but I'm currently getting the same issue

**Comment by eriknw** [comment]
We now build wheels for `cytoolz`, which hopefully fixes this issue. Can you try using version 0.12.0?

**Comment by jrbourbeau** [comment]
Closing this issue as resolves by shipping wheels. Please chime in if this is still an issue.
