### ISSUE TITLE
Incorrect results from cytoolz.sliding_window

### ISSUE THREAD

**Issue by Gerenuk** [pytoolz/cytoolz#123]
The following code incorrectly produces an empty list

    from cytoolz import pipe
    import cytoolz
    import toolz

    pipe(["aaaaa", "bbbbbbbb"],
         cytoolz.curried.map(lambda x:list(cytoolz.sliding_window(7, x))),
         list,
        )

with cytoolz 0.9.0.1 on Python 3.6.

Note that using toolz.sliding_window would give correct results.

**Comment by gwerbin** [comment]
This is because `sliding_window` erroneously raises `StopIteration`, which Python is known for handling poorly.

This is the fix I use in my code:

```python
def fixed_sliding_window_fixed(n, s):
    try:
        yield from cytoolz.sliding_window(n, s)
    except StopIteration:
        yield from ()
```

Usage:

```python
import cytoolz

cytoolz_result = cytoolz.pipe(
    ["aaaaa", "bbbbbbbb"],
    cytoolz.curried.map(lambda x: list(fixed_sliding_window(7, x))),
    list
)

toolz_result = toolz.pipe(
    ["aaaaa", "bbbbbbbb"],
    toolz.curried.map(lambda x: list(toolzsliding_window(7, x))),
    list
)

assert cytoolz_result == toolz_result
```

**Comment by gwerbin** [comment]
This seems to be an issue only when the window is too long for the item being iterated over. It would be nice if `sliding_window` failed more gracefully here.

**Comment by eriknw** [comment]
Fixed!  Thanks all.
