### ISSUE TITLE
Wheels via Wheelwright

### ISSUE THREAD

**Issue by honnibal** [pytoolz/cytoolz#125]
Hi all,

Thanks for your work on this --- we've been happy users of cytoolz in our projects for some time.

Recently we did some work to get wheels up for our libraries. We'd love to help cytoolz get wheels up as well. We made a utility that makes this rather easy, based on Matthew Brett's multibuild: https://github.com/explosion/wheelwright

Once you set up your CI passwords, all you have to do on each release is run something like `python run.py build pytoolz/cytoolz v0.10.0`. The wheels will be built on Travis CI and Appveyor, and uploaded to a Github release on your wheelwright repository. You can then run `python run.py download cytoolz-v0.10.0` and you'll get the files locally, so that you can upload them with something like `twine upload wheels/cytoolz-v0.10.0/*.whl`

**Comment by filips123** [comment]
@pytoolz @eriknw Any update? Can you set up and provides wheels?

**Comment by eriknw** [comment]
Certainly.  This seems like a good approach.  Sorry for letting this sit for so long.

**Comment by filips123** [comment]
@eriknw Any update about this? Building manually on Windows is not something that most users would won't as it requires you to install Visual Studio Build Tools. So wheel for Windows would be really needed.

**Comment by ZechyW** [comment]
(@eriknw @pytoolz) Hi, any chance we could get an update on the availability of wheels (esp. for Windows) please?

**Comment by eriknw** [comment]
We now build wheels for `cytoolz`.  `cibuildwheel` FTW! :tada:

(sorry this took so long to figure out)
