### ISSUE TITLE
Can't install Cytoolz on Windows 7

### ISSUE THREAD

**Issue by shaked571** [pytoolz/cytoolz#126]
I am using python 3.6.2 on a windows 7, I already installed Visual building tools for both 15 (and 17) on my machine but I keep receiving the following error:
    copying cytoolz\tests\test_signatures.py -> build\lib.win-amd64-3.6\cytoolz\
tests
    copying cytoolz\tests\test_utils.py -> build\lib.win-amd64-3.6\cytoolz\tests

    running build_ext
    building 'cytoolz.dicttoolz' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\cytoolz
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe
/c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\python_env\include "-IC:\Program Files
(x86)\Microsoft Visual Studio\Shared\Anaconda3_64\include" "-IC:\Program Files (
x86)\Microsoft Visual Studio\Shared\Anaconda3_64\include" "-IC:\Program Files (x
86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft
 Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10
\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6\
include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\share
d" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Prog
ram Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" /Tccytoolz/dicttoolz
.c /Fobuild\temp.win-amd64-3.6\Release\cytoolz/dicttoolz.obj
    dicttoolz.c
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.ex
e /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPA
TH:c:\python_env\libs "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\S
hared\Anaconda3_64\libs" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studi
o\Shared\Anaconda3_64" /LIBPATH:c:\python_env\PCbuild\amd64 "/LIBPATH:C:\Program
 Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Fil
es (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program
Files (x86)\Windows Kits\10\lib\10.0.17763.0\ucrt\x64" "/LIBPATH:C:\Program File
s (x86)\Windows Kits\NETFXSDK\4.6\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\W
indows Kits\10\lib\10.0.17763.0\um\x64" /EXPORT:PyInit_dicttoolz build\temp.win-
amd64-3.6\Release\cytoolz/dicttoolz.obj /OUT:build\lib.win-amd64-3.6\cytoolz\dic
ttoolz.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\cytoolz\dictt
oolz.cp36-win_amd64.lib
    fatal error C1001: An internal error has occurred in the compiler.
    (compiler file 'f:\dd\vctools\compiler\utc\src\p2\main.c', line 246)
     To work around this problem, try simplifying or changing the program near t
he locations listed above.
    Please choose the Technical Support command on the Visual C++
     Help menu, or open the Technical Support help file for more information

    build\temp.win-amd64-3.6\Release\cytoolz/dicttoolz.obj : fatal error LNK1000
: Internal error during IMAGE::Pass1

      Version 14.00.23026.0

      ExceptionCode            = C0000005
      ExceptionFlags           = 00000000
      ExceptionAddress         = 4E003D83 (00000000) "C:\Program Files (x86)\Mic
rosoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe"
      NumberParameters         = 00000002
      ExceptionInformation[ 0] = 00000008
      ExceptionInformation[ 1] = 4E003D83

    CONTEXT:
      Eax    = 0F60A12E  Esp    = 0022E0E4
      Ebx    = 00000000  Ebp    = 0022E108
      Ecx    = 0022E10C  Esi    = 00000001
      Edx    = 0000000C  Edi    = 00000000
      Eip    = 4E003D83  EFlags = 00010246
      SegCs  = 00000023  SegDs  = 0000002B
      SegSs  = 0000002B  SegEs  = 0000002B
      SegFs  = 00000053  SegGs  = 0000002B
      Dr0    = 00000000  Dr3    = 00000000
      Dr1    = 00000000  Dr6    = 00000000
      Dr2    = 00000000  Dr7    = 00000000
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\B
IN\\x86_amd64\\link.exe' failed with exit status 1000

    ----------------------------------------
Command "c:\python_env\scripts\python.exe -u -c "import setuptools, tokenize;__f
ile__='C:\\Users\\rg60622\\AppData\\Local\\Temp\\pip-install-q8erdq95\\cytoolz\\
setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\
n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\U
sers\rg60622\AppData\Local\Temp\pip-record-78epram2\install-record.txt --single-
version-externally-managed --compile --install-headers c:\python_env\include\sit
e\python3.6\cytoolz" failed with error code 1 in C:\Users\rg60622\AppData\Local\
Temp\pip-install-q8erdq95\cytoolz\

**Comment by eriknw** [comment]
We now build wheels for `cytoolz`, which hopefully fixes this issue.  Can you try using version 0.12.0?

**Comment by shaked571** [comment]
Thanks for the answer, but I don't work with windows machines anymore. So I can't even see if it would work.

**Comment by jrbourbeau** [comment]
Closing this issue as resolves by shipping wheels. Please chime in if this is still an issue.
