### ISSUE TITLE
Segmentation fault when using keymap on os.environ

### ISSUE THREAD

**Issue by CMCDragonkai** [pytoolz/cytoolz#127]
See here:

```py
import os
from cytoolz import dicttoolz

parameters_extra = dicttoolz.keymap(
    lambda k: {
        env_prefix + 'PARAMETERS_MODEL_TYPE': 'model_type',
        env_prefix + 'PARMAETERS_CLASS_COUNT': 'class_count',
        env_prefix + 'PARAMETERS_IMAGE_SIZE': 'image_size',
        env_prefix + 'PARAMETERS_CHANNEL_COUNT': 'channel_count',
        env_prefix + 'PARAMETERS_CHANNEL_MEAN': 'channel_mean',
        env_prefix + 'PARAMETERS_CHANNEL_STDDEV': 'channel_stddev'
    }.get(k, k), os.environ)
```

I have to end up converting it to a dictionary first via `vars(os.environ)`. Which is fine, but shouldn't result in a segfault if I don't.

**Comment by eriknw** [comment]
Oh no!  Thanks for the report.  I'll get this fixed, and we're past due for a release.

**Comment by eriknw** [comment]
I'm able to reproduce this, but I'm stumped as to why this is segfaulting.  Interestingly, `os.environb` (the bytes version) works.

**Comment by eriknw** [comment]
Fixed!  Thanks so much for submitting the bug report.
