### ISSUE TITLE
make cython an install time dependency and do not ship .c files in sdist

### ISSUE THREAD

**Issue by tacaswell** [pytoolz/cytoolz#134]
The .c files generated by cython are not forward compatible so the current sdist will not install on cpython master (and given the errors, I assume 3.8b4, but I have not tried). 

Having a cython dependency when installing from source is not too bad (cython can be pip-installed and you need a compiler either way) and wheels can be used to serve users who need to have no install time dependencies.

This is the opposite request of #4.

Installing from the repository works correctly.

**Comment by eriknw** [comment]
Oh, I see.  Thanks for the explanation @tacaswell.  It's probably not so bad to had a dependency on Cython.  I'll try to get this resolved and published on Python 3.8 in a week or two.

**Comment by tacaswell** [comment]
Another option is what skimage does.  If cython is available, they re-cythonize otherwise fallback to the bundled c.

**Comment by eriknw** [comment]
That seems pragmatic.

**Comment by eriknw** [comment]
Thanks for the suggestion @tacaswell.

Please see https://github.com/pytoolz/cytoolz/pull/137

**Comment by eriknw** [comment]
Done!  Thanks for the insight @tacaswell that Python 3.8 failed due to Cython's `*.c` files not being forward compatible.  (This isn't Cython's fault.  Python changed.)

Cython is an optional dependency for `pip install cytoolz`.

Use `pip install 'cytoolz[cython]'` to require Cython.

**Comment by tacaswell** [comment]
Thanks!
