### ISSUE TITLE
cytoolz.curry missing _partial attribute

### ISSUE THREAD

**Issue by groutr** [pytoolz/cytoolz#141]
Ran across this modifying dask to use cytoolz when available.  dask uses the _partial attribute of a curry instance to normalize a function. However, cytoolz doesn't implement this _partial attribute.

cytoolz needs to expose a _partial attribute, even if it doesn't use it internally.

**Comment by llllllllll** [comment]
I don't think it is fair that dask is using a private attribute. Can it do what it needs to do without using the private state of the curry object?

**Comment by groutr** [comment]
@llllllllll that's a good point. The function that is the culprit in dask is `_normalize_function`.  Either cytoolz needs to change or pytoolz needs to change.
In studying the attributes, it's not possible to write code that works with both cytoolz and pytoolz that inspect the underlying function args/kwargs.

Cytoolz stores the function, args, and kwargs as public facing attributes of the class (but no _partial attribute).

Pytoolz wraps everything in self._partial. The way to access the args/kwargs seems to be accessing those attributes from partial instance. Pytoolz would need to store the `func`, `args`, and `keywords` attributes that cytoolz stores.  I think this is the better route, and I can open a PR against toolz.

**Comment by groutr** [comment]
This is no longer an issue. closing.
