### ISSUE TITLE
Please publish linux `.whl`s

### ISSUE THREAD

**Issue by ptarjan** [pytoolz/cytoolz#158]
Hi! Sadly your package contains some `.so` files which aren't reproducible across machines so I'd prefer if you could publish a `.whl` which means I won't have to compile you constantly and get cache hits. Thanks!

**Comment by eriknw** [comment]
Oh, thanks for the reminder!  I forgot to do it for latest release.  I'll at least upload Linux wheels soon, and then I'll try to figure out cibuildwheel.  My bad!

**Comment by eriknw** [comment]
Done! :tada:
