### ISSUE TITLE
ERROR during installation with Python 3.11 : "RuntimeError: Cython required to build dev version of cytoolz"

### ISSUE THREAD

**Issue by tsarbuig** [pytoolz/cytoolz#190]
Hey guys, I know there is a lot of messages about this, but I don't find any way to install this on Python 3.11 on MacOS

I have this error :  
![image](https://user-images.githubusercontent.com/70858574/207869322-c9d0a8b7-81f4-4a81-bf02-5de03ae2db4f.png)

I tried all the methods I found with no luck... If anyone can help me that would be amazing

Thanks guys !

**Comment by eriknw** [comment]
Oh, right, I forgot to release with Python 3.11 wheels. My bad! I'll release today with Python 3.11 wheels. Thanks for the report @tsarbuig

**Comment by tsarbuig** [comment]
> Oh, right, I forgot to release with Python 3.11 wheels. My bad! I'll release today with Python 3.11 wheels. Thanks for the report @tsarbuig

Thanks a lot bro... but if you could then explain me step by step how to solve this problem, you would be an ANGEL :) thanks bro

**Comment by tsarbuig** [comment]
did you do it @eriknw ? :)

**Comment by eriknw** [comment]
Got it! Try installing `cytoolz` version 0.12.1 now; for example, `pip install cytoolz==0.12.1`.

Sorry for the delay. Jetlag got the better of me.

**Comment by tsarbuig** [comment]
thanks bro that's awesome :)
