### ISSUE TITLE
Provide Python 3.12 wheels

### ISSUE THREAD

**Issue by michprev** [pytoolz/cytoolz#203]
Since Python 3.12 is already a stable release, It would be nice to provide pre-built wheels. cibuildwheel supports building Python 3.12 wheels in version [v2.16.2](https://github.com/pypa/cibuildwheel/releases/tag/v2.16.2).

**Comment by eriknw** [comment]
Excellent suggestion, thanks for the nudge. My bad. Will do!

**Comment by 30ThreeDegrees** [comment]
Im not sure if this is related to needing a 3.12 wheel but im receiving an error when trying to pip install on python 3.12

`Collecting cytoolz
  Using cached cytoolz-0.12.2.tar.gz (601 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: toolz>=0.8.0 in ./venv/lib/python3.12/site-packages (from cytoolz) (0.12.0)
Building wheels for collected packages: cytoolz
  Building wheel for cytoolz (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for cytoolz (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      [1/5] Cythonizing cytoolz/utils.pyx
      [2/5] Cythonizing cytoolz/dicttoolz.pyx
      [3/5] Cythonizing cytoolz/functoolz.pyx
      [4/5] Cythonizing cytoolz/itertoolz.pyx
      [5/5] Cythonizing cytoolz/recipes.pyx
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-312
      creating build/lib.linux-x86_64-cpython-312/cytoolz
      copying cytoolz/_signatures.py -> build/lib.linux-x86_64-cpython-312/cytoolz
      copying cytoolz/_version.py -> build/lib.linux-x86_64-cpython-312/cytoolz
      copying cytoolz/__init__.py -> build/lib.linux-x86_64-cpython-312/cytoolz
      copying cytoolz/compatibility.py -> build/lib.linux-x86_64-cpython-312/cytoolz
      creating build/lib.linux-x86_64-cpython-312/cytoolz/curried
      copying cytoolz/curried/operator.py -> build/lib.linux-x86_64-cpython-312/cytoolz/curried
      copying cytoolz/curried/exceptions.py -> build/lib.linux-x86_64-cpython-312/cytoolz/curried
      copying cytoolz/curried/__init__.py -> build/lib.linux-x86_64-cpython-312/cytoolz/curried
      copying cytoolz/recipes.pyx -> build/lib.linux-x86_64-cpython-312/cytoolz
      copying cytoolz/itertoolz.pyx -> build/lib.linux-x86_64-cpython-312/cytoolz
      copying cytoolz/utils.pyx -> build/lib.linux-x86_64-cpython-312/cytoolz
      copying cytoolz/dicttoolz.pyx -> build/lib.linux-x86_64-cpython-312/cytoolz
      copying cytoolz/functoolz.pyx -> build/lib.linux-x86_64-cpython-312/cytoolz
      copying cytoolz/dicttoolz.pxd -> build/lib.linux-x86_64-cpython-312/cytoolz
      copying cytoolz/itertoolz.pxd -> build/lib.linux-x86_64-cpython-312/cytoolz
      copying cytoolz/functoolz.pxd -> build/lib.linux-x86_64-cpython-312/cytoolz
      copying cytoolz/utils.pxd -> build/lib.linux-x86_64-cpython-312/cytoolz
      copying cytoolz/__init__.pxd -> build/lib.linux-x86_64-cpython-312/cytoolz
      copying cytoolz/cpython.pxd -> build/lib.linux-x86_64-cpython-312/cytoolz
      copying cytoolz/recipes.pxd -> build/lib.linux-x86_64-cpython-312/cytoolz
      creating build/lib.linux-x86_64-cpython-312/cytoolz/tests
      copying cytoolz/tests/test_compatibility.py -> build/lib.linux-x86_64-cpython-312/cytoolz/tests
      copying cytoolz/tests/test_dicttoolz.py -> build/lib.linux-x86_64-cpython-312/cytoolz/tests
      copying cytoolz/tests/test_utils.py -> build/lib.linux-x86_64-cpython-312/cytoolz/tests
      copying cytoolz/tests/dev_skip_test.py -> build/lib.linux-x86_64-cpython-312/cytoolz/tests
      copying cytoolz/tests/test_docstrings.py -> build/lib.linux-x86_64-cpython-312/cytoolz/tests
      copying cytoolz/tests/test_serialization.py -> build/lib.linux-x86_64-cpython-312/cytoolz/tests
      copying cytoolz/tests/test_none_safe.py -> build/lib.linux-x86_64-cpython-312/cytoolz/tests
      copying cytoolz/tests/test_signatures.py -> build/lib.linux-x86_64-cpython-312/cytoolz/tests
      copying cytoolz/tests/test_tlz.py -> build/lib.linux-x86_64-cpython-312/cytoolz/tests
      copying cytoolz/tests/test_curried_toolzlike.py -> build/lib.linux-x86_64-cpython-312/cytoolz/tests
      copying cytoolz/tests/test_dev_skip_test.py -> build/lib.linux-x86_64-cpython-312/cytoolz/tests
      copying cytoolz/tests/test_recipes.py -> build/lib.linux-x86_64-cpython-312/cytoolz/tests
      copying cytoolz/tests/test_curried.py -> build/lib.linux-x86_64-cpython-312/cytoolz/tests
      copying cytoolz/tests/test_inspect_args.py -> build/lib.linux-x86_64-cpython-312/cytoolz/tests
      copying cytoolz/tests/test_itertoolz.py -> build/lib.linux-x86_64-cpython-312/cytoolz/tests
      copying cytoolz/tests/test_functoolz.py -> build/lib.linux-x86_64-cpython-312/cytoolz/tests
      copying cytoolz/tests/test_doctests.py -> build/lib.linux-x86_64-cpython-312/cytoolz/tests
      copying cytoolz/tests/test_embedded_sigs.py -> build/lib.linux-x86_64-cpython-312/cytoolz/tests
      UPDATING build/lib.linux-x86_64-cpython-312/cytoolz/_version.py
      set build/lib.linux-x86_64-cpython-312/cytoolz/_version.py to '0.12.2'
      running build_ext
      building 'cytoolz.dicttoolz' extension
      creating build/temp.linux-x86_64-cpython-312
      creating build/temp.linux-x86_64-cpython-312/cytoolz
      x86_64-linux-gnu-gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/home/james/Documents/code/wozinga/wallet_activation_node/venv/include -I/usr/include/python3.12 -c cytoolz/dicttoolz.c -o build/temp.linux-x86_64-cpython-312/cytoolz/dicttoolz.o
      cytoolz/dicttoolz.c:29:10: fatal error: Python.h: No such file or directory
         29 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cytoolz
Failed to build cytoolz
ERROR: Could not build wheels for cytoolz, which is required to install pyproject.toml-based projects
`

**Comment by pablogamboa** [comment]
I second this, cytoolz is the only dependency now preventing us from upgrading to 3.12 🙏

**Comment by 30ThreeDegrees** [comment]
@eriknw Life gets like that at times and no stress when your ready and able to is fine for me as I just downgraded python in the mean time, also thanks for looking into it I cant speak for everyone but for me personally I really appreciate it.

And I hope everything continues to get better for you in your personal life.

**Comment by eriknw** [comment]
Aw, thanks for the kind words! And for the record, most of my adventures the last few months have been incredible ;)

Anyway, I'm doing a pre-release right now to see if CI scripts still work like they're supposed to. I'll follow up and do a release tomorrow 🤞

**Comment by pablogamboa** [comment]
@eriknw thank you for your work! Hope everything goes well

**Comment by eriknw** [comment]
Closing. `cytoolz` 0.12.3 has approximately 10_000 wheels built and available on PyPI, including wheels for Python 3.12 :rocket:
