### ISSUE TITLE
Please build wheels for python 3.13

### ISSUE THREAD

**Issue by zackw** [pytoolz/cytoolz#209]
It appears that your intent is to support python 3.13 in the just-released cytoolz 1.0, but your CI process is still only building wheels for 3.8 through 3.12.  Please add 3.13 to the set of CPython versions for which you build wheels.

**Comment by mowshon** [comment]
This error occurred to me in Docker as well. Using `python:3.13-slim-bookworm`
Exactly if there is a `slim` version of the image.

If I change it to:

```Dockerfile
FROM python:3.13-bookworm
```

Everything works fine.
Except that the image size is larger if I remove the **slim**...

**Comment by ardevd** [comment]
Would also appreciate wheels for Python 3.13.

**Comment by ardevd** [comment]
I've tried reaching out to maintainers, but no response so far. Our project is unfortunately a bit stuck currently due to the lack of wheels for 3.13.

**Comment by eriknw** [comment]
I just released 1.0.1 with Python 3.13 wheels. It'll take a few minutes for CI to run to upload to PyPI.

Our bad for the delay! I thought we updated to 3.13 when we released in October 🤷‍♂️. Thanks for the reminders, and sorry for this being a busy time of year.
