### ISSUE TITLE
Release GIL?

### ISSUE THREAD

**Issue by mrocklin** [pytoolz/cytoolz#53]
Is there anything stopping us from doing this?  Is it unsafe in any way?

**Comment by jakirkham** [comment]
+1

**Comment by stestagg** [comment]
In general these functions seem to be dealing with Python containers, which are only thread-safe if used in conjunction with the GIL

**Comment by frol** [comment]
It is quite easy to get a sense on whether you can release GIL in Cython, that is by using

```
$ cython --annotate "xxx.pyx"
```

It will produce a colorized HTML report with yellow highlighting where Python objects are involved: http://cython.readthedocs.io/en/latest/src/quickstart/cythonize.html#determining-where-to-add-types

Looking at the reports Cython produced for cytoolz, I can say that it will require quite some effort to get to the state when GIL can be released.

**Comment by eriknw** [comment]
Agreed.  Thanks for the feedback.  Closing this issue, as releasing the GIL is unrealistic at the moment.
