### ISSUE TITLE
what about cytoolz 0.7.4 (on par with toolz 0.7.4) ?

### ISSUE THREAD

**Issue by stonebig** [pytoolz/cytoolz#70]

**Comment by eriknw** [comment]
Yeah, this is on me.  My bad.  After a very busy summer, I chose to focus on self-betterment during the last month or so.

Thanks for the gentle prod.  I'll update `cytoolz` sometime this week (unless somebody beats me to it ;) )

**Comment by eriknw** [comment]
Done.

I encountered technical difficulties last week, which delayed my ability to get to this.  These mysteriously disappeared today.  Anyway, enjoy, and let me know if you find any issues!

**Comment by stonebig** [comment]
thanks !
