### ISSUE TITLE
Add & Push tags for Releases

### ISSUE THREAD

**Issue by mindw** [pytoolz/cytoolz#80]
0.8.0 etc.

**Comment by eriknw** [comment]
Good and reasonable suggestions.  Will do.  I'm sorry for slacking.

**Comment by eriknw** [comment]
Added: https://github.com/pytoolz/cytoolz/releases

We also now have a `release` branch that contains the built `*.c` files whenever we do a release.  `release` will never merge into `master` so as to not clutter it's history with `*.c` files created by Cython.

Feel free to re-open if you notice anything amiss.
