### ISSUE TITLE
Setup github releases

### ISSUE THREAD

**Issue by gdonval** [pytoolz/cytoolz#81]
Please [setup releases](https://help.github.com/articles/creating-releases/) on Github as you did with `Toolz`, it is better for packaging than cloning the whole repository and history and then checking out a given tag.

**Comment by eriknw** [comment]
Will do.  Packaging is important.  I'm sorry for slacking (although the occasional slacking is good for my well-being).

**Comment by eriknw** [comment]
Added: https://github.com/pytoolz/cytoolz/releases

We also now have a `release` branch that contains the built `*.c` files whenever we do a release.  `release` will never merge into `master` so as to not clutter it's history with `*.c` files created by Cython.

Feel free to re-open if I messed something up or need to do more.
