### ISSUE TITLE
Compilation fails with Cython>=0.25

### ISSUE THREAD

**Issue by achidlow** [pytoolz/cytoolz#87]
`Cython.Compiler.Options.directive_defaults`, which is used in `setup.py` to turn `embedsignature` and `binding` on [has been removed](https://github.com/cython/cython/blob/master/CHANGES.rst#other-changes-1). It's replace `get_directive_defaults()` doesn't look like it will do the same thing. 

I propose setting compiler directives via [compiler_directives](http://cython.readthedocs.io/en/latest/src/reference/compilation.html#in-setup-py) option to `cythonize`. It should do exactly the same thing?

**Comment by eriknw** [comment]
I went with `get_directive_defaults()` (before I saw this issue, sorry), which returns a dict and appears to do the same thing, but first does some testing on the options.  `cythonize(compiler_directive=...)` as you recommend would work as well, and is arguably cleaner.

Thanks for the report!
