### ISSUE TITLE
unified testing via `toolz`

### ISSUE THREAD

**Issue by eriknw** [pytoolz/cytoolz#9]
In the interest of development speed, the tests from `toolz` were basically just copied over to `cytoolz`.  This is not easily sustainable.  We would like all toolz-related tests to reside in `toolz`.  Moreover, we would like a way to run the tests for toolz such as `toolz.tests.run()`, and to provide an optional toolz-like package on which to run the tests such as `toolz.tests.run(cytoolz)`.

This issue does not cover testing CyToolz C API, which I regard as very low priority at the moment.

**Comment by llllllllll** [comment]
We could look at writing the tests in the structure of the CPython tests in modules like tests/test_operator.py that need to test both the c and python implementations.

**Comment by eriknw** [comment]
Closing.  We have been getting by with `$ make copytests` to copy tests from `toolz`, adding `cytoolz`-specific tests in new files, and back-porting tests to `toolz` as necessary.
